project_id = "cdrysmuwccvmvruxoaza"

[functions.generate-blog]
verify_jwt = false

[functions.generate-social]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-product]
verify_jwt = false

[functions.analyze-seo]
verify_jwt = false

[functions.schedule-post]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = false

[functions.accept-team-invitation]
verify_jwt = false

[functions.generate-website]
verify_jwt = false

[functions.audit-website]
verify_jwt = false
